name: Run Bot.py with Virtual Environment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate the virtual environment
        run: source venv/bin/activate

      - name: Install required libraries
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyTelegramBotAPI==4.14.0
          python -m pip install numpy==1.26.2
          python -m pip install imageio==2.33.1
          python -m pip install Pillow==10.1.0
          python -m pip install requests==2.31.0
          sudo apt-get install ffmpeg
      - name: Run Bot.py
        run: |
          # Ensure only one instance of the bot is running
          flock -n ./lockfile python Bot.py
        env:
          TELEGRAM_BOT_API_ID: ${{ secrets.TELEGRAM_BOT_API_ID }}